### ISSUE TITLE
[request] README or some other documentation for installation and inclusion in neovim/vim

### ISSUE THREAD

**Issue by megalithic** [jaredramirez/elm-language-server#2]
Thanks so much for this project @jaredramirez! I'd love to see some sort of documentation outlining installation procedures and possibly even config snippets for inclusion/usage within neovim/vim.

I'd be happy to help test (i use neovim for everything)

**Comment by jaredramirez** [comment]
That's definitely on the roadmap, but this project is still in the very early stages and is not really usable right now. Once it gets to an alpha stage, I'll definitely add some documentation and let you know so you can give it a shot!

(I know already responded to your message on twitter, but also responding here in case others have this same question)
